### ISSUE TITLE
[Bug]: Not an editor command "PackerInstall"

### ISSUE THREAD

**Issue by 30-silver** [ChristianChiarulli/LunarVim#1129]
### Problem description

1. Run the script for neovim in readme.md
2. That's about it

I can't install this because it gives me this error. I'm using Neovim on Linux Mint (Cinnamon)

### LunarVim version

latest

### Neovim version (>= 0.5)

0.4.3

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Uzaaft** [comment]
@30-silver  Could you go ahead and update your neovim version? Ref the readme:
```
...
Make sure you have the newest version of Neovim (0.5).
```

**Comment by rafamadriz** [comment]
@30-silver Go ahead a use this ppa https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable since Linux Mint still has 0.4
Closing this since you're using the wrong neovim version. If you need more help you can keep commenting.

**Comment by jamessouth** [comment]
This is still happening. On Arch, installed `neovim-0.5.0-1`, ran the install script, it kicked out asking for `pip`, installed `pip`, script runs to completion, no errors, run `nvim` per wiki then `:PackerInstall`, get this error. `:PackerSync` also errors. I tried the steps in [this comment](https://github.com/ChristianChiarulli/LunarVim/issues/198#issuecomment-811658134), still get error. Packer is installed at `~/.local/share/lunarvim/site/pack/packer/start/packer.nvim`.

**Comment by jamessouth** [comment]
The wiki install page should be changed to say 'run `lvim` then `:PackerInstall` and/or `:PackerSync`'. `Install` did nothing but it didn't error in `lvim`, `Sync` synced 28 plugins and said 'up to date!'.

**Comment by rebuilt** [comment]
The wiki will be purged soon.  It has a lot of outdated information.  Documentation resides here.  https://www.lunarvim.org/01-installing.html#manual-install.  I'll update the wiki with a link to that site.

**Comment by rebuilt** [comment]
By default PackerInstall won't trigger a user interface event but it should still download your plugins in the background.  Run PackerStatus to confirm.

**Comment by jamessouth** [comment]
Those docs (and the readme) also say to run `nvim` not `lvim`.

There are several packages listed in the `Manual Install` section that are not installed by the `One Command` install script. Are they still necessary?

**Comment by rebuilt** [comment]
Can you make a pr against this repo with your suggested changes please.  https://github.com/LunarVim/lunarvim.org

**Comment by jamessouth** [comment]
Ok I'll come up with something for you.

**Comment by jamessouth** [comment]
In the install script, the `install pip` lines have been commented out since they were added and the `installextrapackages` function is never called, which is why I don't have `ripgrep`, `fzf`, `neovim-remote`, or `tree-sitter-cli`. My plan for writing canonical install docs is to more-or-less combine a stripped-down install script (since it is in such flux) with the manual install commands to form `the way`. Then the user would just follow commands for their OS and choose `master` or `rolling`. I was going to submit a PR of a new install script, along with the docs PR, since they go hand in hand. When the install process is more stable (e.g. `ranger` and `ueberzug` were just removed < 2 weeks ago) the automation of the script can always be restored, and the docs adjusted accordingly. I thought this would be sensible since among the readme, docs, wiki, and script there is some conflict.

The alternative is to (re-)engage these install functions in the script now, and, IMO, remove those commands from the docs. Is it imperative to have manual install instructions? I think so only as part of `the way`, in conjunction with the script that will not install those packages, just handle repo cloning and file system commands.

**Comment by jamessouth** [comment]
If I submitted a PR for the install script, would it be considered? I can fix typos in the docs if you want, but there would still be a difference between the results of the automatic and manual installs, and thus the docs would not be much improved. I have forked and made some changes and run my local script to finish my own install. So far I have:

* instead of calling `asktoinstallnode` and `asktoinstallpip`, just call `installnode` and `installpip`
* add (apparently) missing packages listed in `manual install` to the various `installon[OS]` functions
* call `installextrapackages`, which in turn calls the appropriate `installon[OS]` function

`neovim-remote` warned about not being on the PATH - I can see that the script formerly modified PATH but those lines have been commented out. `tree-sitter-cli` was a pain but I got it installed with the `n` package - if users did that prior to running the script it wouldn't error anymore. 

If these sorts of changes are acceptable, it would be easier to write coherent docs about the install process. What do you think?
