### ISSUE TITLE
More reasonable install dir ? 

### ISSUE THREAD

**Issue by midnightexigent** [ChristianChiarulli/LunarVim#1214]
The current installation lives in `~/.local/share/lunarvim` which is kind of weird

Any reason it can't be somewhere more common like `~/.lunarvim`, `~/.lvim` or even `~/.config/lvim` with the user config in `~/.config/lvimrc` ?

**Comment by ChristianChiarulli** [comment]
I wouldn't recommend putting any config or data directories in the home directory. I'm not sure why you would would want it collocated with your repo since the core of lunarvim should be left unedited by the user, unless you want to fork it or something.

**Comment by rebuilt** [comment]
`~/.local/share/` is a standard directory to place these kind of files.  It conforms to the xdg specification 

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by midnightexigent** [comment]
I guess it's just not common for config frameworks to be in located in `~/.local/share` (ex. `doom-emacs`, `zsh-znap`, `oh-my-zsh` etc.) 

`~/.local/share/lunarvim/site` definitely belongs there tho

**Comment by rebuilt** [comment]
The config folder is designed as a place to put user-editable files.  LunarVim has separated out the configuration to `.config/lvim`.  Data files live in $XDG_DATA_HOME which is $HOME/.local/share.  The application is nvim so it gets placed somewhere else.  The way I see it, LunarVim is adhering to the xdg standard.

**Comment by ChristianChiarulli** [comment]
They should all probably start conforming to the xdg standard.

**Comment by midnightexigent** [comment]
The standard says that `~/.local/share/` is the location where "user-specific data files should be stored". Which can honestly mean anything  (hell, some apps store the log files there), tho, **usually, apps tend to use this directory to store some sort of state that can be rebuilt whenever deleted** which is why I believe that `~/.local/share/lunarvim/site` definitely belongs there but `lvim` doesn't 

The way it currently is, is probably just fine, I am just saying that a `~/.lvim` makes it look more familiar, has less side effects since the binary can be there (`~/.lvim/bin/` which is also a common pattern) and is probably more flexible for the future

**Comment by ChristianChiarulli** [comment]
I understand the familiarity aspect to some degree but the way I see it there are 4 directories I can use (before I use a package manager to install in the future)

`~` <- this is a terrible option because it clutters up your home directory and should be avoided at all costs
`~/.config` <- this is for a users config something they can check into version control and have complete control over
`~/.cache` <- this is for caching stuff so pretty obviously not a good choice
`~/.local/share` <- last option I had, has the nice benefit of users not really being aware that this is a thing so they won't mess with it, and stick to their config in `~/.config`

I think it's a pretty sane place for it to be when you consider the options. I'm willing to listen to opinions but I can tell you this, if I would have put it in `~/.lunarvim` I would've had tons of people complaining about cluttering up their home dir. 

So maybe I see this as the least bad way of doing things imo, even if it breaks convention with other more established frameworks.

**Comment by rebuilt** [comment]
>  **usually, apps tend to use this directory to store some sort of state that can be rebuilt whenever deleted**

I'll give you my personal opionion because I'm not speaking officially for LunarVim.

You use the word 'app' here to describe LunarVim.  And that gets to a more existential question.  Is LunarVim an app?  When you take away Neovim from LunarVim do you still have an app?  

There was a time in the development of unix where the pipe command didn't exist.  All programs were small because they literally didn't have the ram or processing power to be any bigger.  But then Douglas McIlroy comes up with the idea of chaining the output of one command to the input of another.  And by this mechanism, a whole new world of complex software is born.

 The way I see LunarVim is, not as stand-alone software, but as the pipe command chaining together software.  It sets up the rules, the order and makes choices about which software gets run and how.   But it wouldn't be anything without all the other software we pull together.

LunarVim exists in this middle realm, where it's not user configuration files and it's not stand-alone software.  It's the glue that binds these things together.  So yes, we don't do things like other neovim configurations.  And it's a deliberate choice because LunarVim is existentially different from other configurations.  

So, no.  I don't think it belongs in the configuration directory because it's not user configuration.  And I don't think it needs a binary folder because it's not a stand-alone app.  

PS.  We owe a lot to the people who make neovim, and plugins, and language servers, and formatters and linters, and to the people creating the apis and protocols that ultimately allow us to compose great software from disparate sources.  And of course to the 130 contributors that have helped improve LunarVim.

**Comment by midnightexigent** [comment]
@ChristianChiarulli : Interesting, cool of you to elaborate. tho crazy on how points of views can differ, how I see it is that multiple folders in the home directory is a perk since it allows you to immediately tell what is installed. Anyways, this seems like a philosophical debate and I understand your reasoning on putting `lunarvim` where it is which further backed by @rebuilt 's comment



> before I use a package manager to install in the future

About that, would it be impossible to make LunarVim into a neovim plugin ? Alternatively I was thinking of writing a LunarVim manager (cli) with commands such as `lvim update`, `lvim follow nightly | stable`, `lvim -- <pass args to nvim>` etc. Providing a package becomes easy because the cli does all of the heavy lifting. This can be further extended in the future if LunarVim becomes segmented into multiple components `lvim component add | remove <component-name>`

Thoughts ?

**Comment by ChristianChiarulli** [comment]
@midnightexigent I like the idea, I think during the latest refactor someone from the team noticed with a little tweaking you could pull lunarvim in as a plugin. 

I think having some cli commands like `lvim --update` would be extremely valuable and would be a welcome addition. The component idea while a little more difficult to implement would also be really cool (potentially a 2.0 feature).
