### ISSUE TITLE
:PackerInstall error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by KarolusD** [ChristianChiarulli/LunarVim#203]
![Screenshot 2021-03-31 at 11 09 05](https://user-images.githubusercontent.com/35146988/113120410-da547700-9211-11eb-8f26-63af0be88503.png)

**Comment by jameswalmsley** [comment]
Ensure that ~/.cache/nvim has the right permissions.
(chmod 755 that directory...). I had this issue when that folder didn't already exist and nvim creates the folder itself with out the correct fs flags so that you can't create new files inside it.

Otherwise its some other issue.

But I think based on the Permission Denied text its because packer cannot create is lot file.

**Comment by ChristianChiarulli** [comment]
Yea permissions errors should not be the fault of packer.

**Comment by KarolusD** [comment]
Right permissions did the job and allowed to use :PackerInstall comand, thanks.
But still, there is some problem with lua callback:
![Screenshot 2021-04-02 at 15 09 04](https://user-images.githubusercontent.com/35146988/113421098-ca33c780-93ca-11eb-90d4-c979472927b8.png)

**Comment by KarolusD** [comment]
I guess it's the same issue: #218 
commenting lines 76 to 87 inside ~/.local/share/nvim/site/pack/packer/start/nvim-treesitter/lua/nvim-treesitter/indent.lua
gets rid of that error.
