### ISSUE TITLE
Cannot make format on save.

### ISSUE THREAD

**Issue by joaop-oliveira1** [ChristianChiarulli/LunarVim#224]
Whenever I save a typescript file prettier does not format my code, now I don't have any preferences over Lua Formating over Prettier or vice-versa, but where can i find the file or the settings to custom my format settings?

Thanks in advance!

**Comment by ChristianChiarulli** [comment]
look into the efm-langserver settings, should explain things, the code is pretty easy to follow.

**Comment by daniel-bray** [comment]
I haven't been able to get formatting to work for any file type. I ended up adding the neoformat plugin to format my code. 

[](https://github.com/sbdchd/neoformat )

**Comment by ChristianChiarulli** [comment]
whats your filetype? @daniel-bray

**Comment by daniel-bray** [comment]
> whats your filetype? @daniel-bray

I have tried .js .ts .py and .lua

When saving I get the following errors:

Error detected while processing BufWritePre Autocommands for "*.js":
E5108: Error executing lua ...neovim/HEAD-691a72b_2/share/nvim/runtime/lua/vim/lsp.lua:1137: table index is nil

I have watched every video of yours since you moved from init.vim to init.lua, checked all the settings in the lua/lsp folder for those file types. I can't seem to figure out what is going on. Language servers are also installed.

**Comment by ChristianChiarulli** [comment]
Did you :LspInstall efm?

**Comment by daniel-bray** [comment]
I have the following language servers installed

![image](https://user-images.githubusercontent.com/5752937/113514008-ddad7280-9531-11eb-92ae-32670de4279c.png)

**Comment by ChristianChiarulli** [comment]
It’s not identifying a root. Throw a .git/ in there and try.

**Comment by michalens** [comment]
Same for me. I have set nvim to use `prettier` for ts files in multiple places, but it still doesn't format it according to `.prettierrc.js` . I have .git folder and `tsserver` with `efm` isntalled

**Comment by daniel-bray** [comment]
> It’s not identifying a root. Throw a .git/ in there and try.
> […](#)
> Sent from my iPhone
> On Apr 4, 2021, at 11:38 AM, Daniel J. Bray ***@***.***> wrote: ﻿ I have the following language servers installed — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

BOOM! I got everything working now. for TS/JS I uninstalled typescript and typescript language server ```npm uninstall -g typescript typescript-language-server``` then reinstalled them globally.

For python adding the .git/ worked for me. Thanks for your help @ChristianChiarulli 

@michalens do you have typescript and typescript-language-server installed globally?

**Comment by michalens** [comment]
@daniel-bray I had them install globally, reinstalled, but it didn't help. I don't think it matters, because LSP is using local installation on tsserver in `/lspinstall/` folder

**Comment by michalens** [comment]
And if previously it at least showed errors (like a missing semicolon), right not it neither shows, nor fixes

**Comment by ahmed-rezk-dev** [comment]
It happened to me also.

I got this info by running `:LspInfo`


Clients that match the filetype javascript:
  
```
  Config: tsserver
  	cmd:               /Users/dddd/.local/share/nvim/lspinstall/typescript/node_modules/.bin/typescript-language-server --stdio
  	cmd is executable: False. Please check your path and ensure the server is installed
  	identified root:   /Users/dddd/Development/reacts/playground
  	custom handlers:   textDocument/publishDiagnostics

```

**Comment by ahmed-rezk-dev** [comment]
**First**

So the solution I found is that in `.config/nvim/lua/lsp/efm-general-ls.lua` file is that @ChristianChiarulli is assigning  `javascript/javascriptreact` to an object called `tsserver_args` wiche is empty. You have to set it to use `{prettier, eslint}`, So that the server knows that we going to use these two options for formation and linting 

```
  local tsserver_args = {prettier, eslint}

  javascript = tsserver_args,
  javascriptreact = tsserver_args,
```
**Second**

EFM is using `prettier/eslint` globally which is not common. If you are working in a team. Most of the time they are used locally in the project itself. So nothing is going to work if you don't install them globally. If you want to use them locally. Comment line number `52` uncomment line number `54` as @ChristianChiarulli said there at the file itself.

Hope that's will help :) 👍🏼

**Comment by cj** [comment]
I am having the same issue with `typescripreact` files, everything is configured but it just does not auto format on save.

![CleanShot 2021-05-09 at 11 46 50](https://user-images.githubusercontent.com/1819/117580180-5321db00-b0bc-11eb-9522-16d4969a552f.png)

**Comment by shinymimiq** [comment]
It looks to me that this comment also resolves my auto-formatting issue for JS/JSX
https://github.com/ChristianChiarulli/LunarVim/issues/402#issuecomment-841886426
