### ISSUE TITLE
I can't use Emmet

### ISSUE THREAD

**Issue by marcograhl** [ChristianChiarulli/LunarVim#286]
How Can I enable Emmet < C - y > , is not doing much for me. Anybody uses Emmet with LunarVim and has a hint?

**Comment by rebuilt** [comment]
Assuming you have everything installed correctly, got to ./lua/settings.lua and comment out line 35.  

```bash
-- vim.o.timeoutlen = 100
```

This is tip from the emmet project
```bash

FAQ
    Pressing ctrl+y+, doesn't work

    Probably you set timeoutlen=0. Most of Vim plugins which using key-mappings does not work with timeoutlen=0.
```

**Comment by ChristianChiarulli** [comment]
I recommend emmet-ls, right now you need to globally install `npm i -g emmet-ls`

**Comment by marcograhl** [comment]
Thx for the fast reply, I did install emmet-ls do I need to Install it with Packer too? I mean the use and require you did with the outer plugins? I sometimes get an autocompletion randomly, I don't know if I'm doing the ctrl-y +, right :). Sometimes there is an autocompletion with Lsp Emmet without me doing anything. Im just a little confused, the resulting snippit is wrongly indented as well. I will dig deeper , cause I love the work you put in, its nice to have "default nvim" this beautifull. Thx Chris

**Comment by marcograhl** [comment]
Is there a way I can see if the keybind ctrl-y , is actually being used by emmet?

**Comment by rebuilt** [comment]
```bash
    :nmap for normal mode mappings
    :vmap for visual mode mappings
    :imap for insert mode mappings
```

Try this instead
```bash
:verbose imap <C-y>
```

**Comment by marcograhl** [comment]
Its not mapped to anything weird. I didn't change anything from the starter files. I got Lsp working and its beautifull => love the preview popup window omg. I installed emmet-ls globaly.. mhh is there a step I missed.

**Comment by rebuilt** [comment]
I haven't set it up myself but according to[ the docs](https://www.npmjs.com/package/emmet-ls) you need something like this in your configs

```bash
local nvim_lsp = require'lspconfig'
local configs = require'lspconfig/configs'
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

configs.emmet_ls = {
  default_config = {
    cmd = {'emmet-ls', '--stdio'};
    filetypes = {'html', 'css'};
    root_dir = function()
      return vim.loop.cwd()
    end;
    settings = {};
  };
}

nvim_lsp.emmet_ls.setup{
  on_attach = on_attach;
}
```

**Comment by rebuilt** [comment]
I just set it up for myself.  It looks like its turned 'off' by default.
Uncomment the following line in lua/lsp/emmet-ls.lua, line 18

```bash
on_attach = on_attach
```

**Comment by rebuilt** [comment]
Did the output of the following command change?  
:verbose imap <C-y>

**Comment by rebuilt** [comment]
Make sure emmet is executable from the command line

**Comment by marcograhl** [comment]
how can I see that, what do I need to put into the command line?

**Comment by rebuilt** [comment]
What's the output of 
```bash
which emmet-ls
```

Also make sure you're in an html file and not an html.erb file or something like that.  

What is the output of 
```bash
:LspInfo
```
It should contain an entry for emmet_ls

**Comment by marcograhl** [comment]
/usr/local/bin/emmet-ls 
is the location

here is the image for LspInfo
<img width="1109" alt="Screen Shot 2021-04-22 at 21 09 43" src="https://user-images.githubusercontent.com/20419551/115772242-26c54980-a3af-11eb-80d9-a670d08e00bf.png">

**Comment by rebuilt** [comment]
That looks correct.  Just as a sanity check, have you opened and closed the html file you're testing and are you typing the keybindings in insert mode?

**Comment by rebuilt** [comment]
I think the issue might be me.  I previously had the emmet plugin installed.  I removed emmet from my configuration files but I did not run a clean to delete those folders.  The keybindings were coming from my old emmet folder.  

 https://github.com/mattn/emmet-vim

**Comment by marcograhl** [comment]
I thought I maybe set it up with whichkey for fun... have a good one

**Comment by rebuilt** [comment]
I did end up setting up emmet-ls.  I could not do it with compe.  
The emmet-ls instructions use completion-nvim so that's what I used.  It works very differently than the previous emmet plugin.  To trigger the completion I press Tab+Tab+enter.

![emmet](https://user-images.githubusercontent.com/16025007/115800446-eb407480-a3da-11eb-8750-8affcdffbe9a.gif)

**Comment by marcograhl** [comment]
ok thats awesome, I deleted compe and installed  completion-nvim (via PAcker )but nothing happens. Do I need to change the config in any way? and on the github they say you can use the . key to trigger completion with this setting:
let g:completion_trigger_character = ['.']
where would I put that in neovim. Thanks

**Comment by rebuilt** [comment]
Follow the [setup docs](https://github.com/nvim-lua/completion-nvim) to install completion 
You don't need to set the completion trigger character
You do need these options
```bash
let g:completion_enable_snippet = 'vim-vsnip'

set completeopt=menuone,noinsert,noselect,preview
" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Avoid showing message extra message when using completion
set shortmess+=c
imap <tab> <Plug>(completion_smart_tab)
imap <s-tab> <Plug>(completion_smart_s_tab)

```

This is a very important setting. It enables completion for every document.  Otherwise you have to enable completion per language server.   Read the docs if you prefer to enable with language server.  
```bash
autocmd BufEnter * lua require'completion'.on_attach()
```
make sure you install the language server
```bash
npm install -g emmet-ls
```

Install vsnip and related snip support
https://github.com/hrsh7th/vim-vsnip
https://github.com/rafamadriz/friendly-snippets

```bash
use 'hrsh7th/vim-vsnip'
use 'hrsh7th/vim-vsnip-integ'
use 'rafamadriz/friendly-snippets'
```

If you want more snippets, get them here:
https://github.com/craigmac/vim-vsnip-snippets/tree/master/snippets
Read the vsnip docs to figure out how to install them.



There's a lot to set up and I didn't actually set it up on lunarvim.  I modified my own configs which are still in vimscript syntax.  But if you think it will help you out to look at my configs, they are here:  https://github.com/rebuilt/neovim-config  

I uploaded them just for you :)

**Comment by marcograhl** [comment]
wow, thats great Thank you. I will find some time next week to dive deep. Greetings from Germany and stay save
