### ISSUE TITLE
gopls uses the current file's directory as root, instead of the git root

### ISSUE THREAD

**Issue by Araly** [ChristianChiarulli/LunarVim#388]
When I run LspInfo when working on a file of a go project, it shows that the root for the project is whatever folder the file is in, instead of the actual root of the folder a couple directories up in the tree. It makes gopls behave weirdly as it doesn't find all the references it should, it has only a small part of the project diagnostics, and sometimes is confused about things that should be clear if it knew the right root.

How to I give gopls the right root ?

Thank you

**Comment by ChristianChiarulli** [comment]
we need to resolve exactly how this should work

**Comment by rebuilt** [comment]
The root needs to be the root of a project or it will bug out the language server.  A language server needs to know about a whole project in order to perform actions like renaming a function.  There is a way to fall back to the current directory if a project isn't found.  Someone added that functionality to the efm language server.  But I'm not sure it's a good idea to add that to every language.  https://github.com/neovim/nvim-lspconfig/pull/884/files

**Comment by abzcoding** [comment]
This issue should be fixed now. Feel free to reopen it if it still exists
