### ISSUE TITLE
Update plugins.lua

### ISSUE THREAD

**Issue by pard68** [ChristianChiarulli/LunarVim#478]
I started working on a branch to update plugins.lua, but decided I shouldn't put much work into this without some feedback from others.

It seems to me that the plugins installation method is way to complicated. It requires three separate lines in two different files (sometimes) to get a plugin working. I need a `use` line to install with packer. I need a `require_plugin` line to do... something... and then I need to `require` the plugin's own config file in `init.lua`. In my own neovim config that I was working on before LSP broke me and I just switched to LunarVim, I wrote my own `use` function, `Use` which called `use` and then called `require` if there was a dir/file matching the plugin's name, thus requiring only one line to add a plugin and not three. I wanted to add something like this for LunarVim. Thoughts?

Also, why does `require_plugin` exist? I understand what it does, but I cannot figure out why it exists.

**Comment by rmagillxyz** [comment]
From my understanding the `require_plugin` is used to load that plugin, giving people the option to not load the plugin on initial load but to still have it on hand if needed. That is what the `opt = true` is for; if you look in `~/.local/share/nvim/site/pack/packer` you'll see `opt` and `start`, the plugins in `start` start without a `require_plugin` on initial load. Chris was trying to move away from other projects like `oh my zsh` which have tons of bloat that many people will not use when first starting out. I'm assuming that's why he added the `extras` section too. You have lots of ways stripping things up or down. I remember him saying his last config became a little too opinionated and thick, or something like that. As for your other questions, that wouldn't be up to me, but I hope this helps some.  @pard68

**Comment by pard68** [comment]
Awesome, thanks for that info. That was enough to reason out where in the loading order it needs to be called. I'm a WIP PR to better understand my idea for loading plugins.

**Comment by rebuilt** [comment]
You don't have to use require_plugin if you don't want.  You can just set your plugin to required and it will work.  

For an example of how to take advantage of packer's lazy loading, look here: https://github.com/ChristianChiarulli/LunarVim/pull/416/files

**Comment by rebuilt** [comment]
I messed something up when I submitted it.  I think I should have rebased before marking it ready for merging.  A later commit reverted my changes.   But I'm not 100% sure if this was intentional or not.  I didn't get any feedback about it from Chris.  I'm not sure if he even knows it happened.  I've been trying to figure out if I broke something with that commit.  Someone else used it and said they changed compe to load at launch because the load time for it was noticeable on switching into insert mode.   but other than that, I think it works fine and it improves load time.

**Comment by pard68** [comment]
I don't think it was your doing, because it's not in the master branch's commit history at all. [This](https://github.com/ChristianChiarulli/LunarVim/commit/92b25e4e10c9b1424bd2f6a30336b1121db5eede) is the commit, however it isn't attached to any branches... Very weird.

**Comment by pidgeon777** [comment]
I also think that enabling\disabling plugins could be optimized, for example, when debugging.

Now to enable and configure a plugin, it is required to do this:

For enabling/disabling, in `lua\plugins.lua`:

````lua
use {'plugauthor/plugname', opt = true}
...
require_plugin("pugname")
````

For its custom configuration, in `lua\init.lua`:

````lua
require('lv-plugname')
````

What if the plugin is not enabled? The last lua code would make Neovim crash at startup.

First, I was wondering how could I activate the last require only if the plugin was effectively loaded. I mean something like this:

````lua
ifexist('plugname').require('lv-plugname')
````

Any hint?

**Comment by rebuilt** [comment]
Packer has a built-in functionality to load plugins conditionally.  Use 'cond' for arbitrarily loading plugins based on some boolean value.  Otherwise, you'll end up recompiling to enable/disable plugins.  The tradeoff is that plugins loaded this way wont be lazy loaded. They'll just load at boot time.

**Comment by ChristianChiarulli** [comment]
I had a terrible pattern for doing this. It is much better now.
