### ISSUE TITLE
Does LunarVim support vim-sneak ?

### ISSUE THREAD

**Issue by Kangaxx-0** [ChristianChiarulli/LunarVim#496]
It seems like LunarVim supports vim-sneak already because i was able to search word with `s<char><char>`, however, type semicolon `;` does not go to the next match, neither other keys, also, i could not find the plugin name in lua folder

I am kind of new to neovim, so would be appreciated if you could help :)

**Comment by rebuilt** [comment]
Vim sneak is not installed by default.  You can add it to lunarvim by editing the plugins.lua file.  If you had a previous configuration that included vim-sneak it's possible sneak is being loaded because a folder for it exists in the autoload folder.  If you run :PackerClean or :PackerSync it will delete any plugins not in plugins.lua.

**Comment by rebuilt** [comment]
https://github.com/ChristianChiarulli/LunarVim/issues/498

**Comment by Kangaxx-0** [comment]
Thanks
