### ISSUE TITLE
plugin PackerInstall failed

### ISSUE THREAD

**Issue by binnz** [ChristianChiarulli/LunarVim#585]
![image](https://user-images.githubusercontent.com/31803225/124263093-68b7fc00-db65-11eb-8c27-59b4bc8672d4.png)

After run :PackerInstall command, plugins  installing all failed.
terminal proxy not work, i want to know if exist someplace to set the proxy config, or config the github.com to others, thanks.

**Comment by rebuilt** [comment]
Do you have a slow connection to github or no connection at all? 
What's the output of 
```
# Linux
ping -c 1 github.com

# Windows
ping -n 1 github.com
```

If it's timing out because it's taking too long you can increase the timeout setting for packer.  Look at the packer documentation for 
```
clone_timeout = 60, -- Timeout, in seconds, for git clones
```

https://github.com/wbthomason/packer.nvim#custom-initialization

Also, if you used 'sudo' with the install script, only the root user will have permissions to write to the plugin folder.  Follow the instructions for uninstalling lunarvim and install again without sudo

```
https://github.com/ChristianChiarulli/LunarVim#uninstalling
```

If you have further problems, the correct place for this question is the [packer project.](https://github.com/wbthomason/packer.nvim)

**Comment by rebuilt** [comment]
Also, can you list the output of 
```
:messages
```

That might give you more details for why it's failing.

**Comment by binnz** [comment]
> Also, can you list the output of
> 
> ```
> :messages
> ```
> 
> That might give you more details for why it's failing.

in the begining i write ip of github.com in /etc/hosts,  if not work. Then i use terminal proxy, but not drop the config in /etc/hosts, so it not work still. already fix it, thanks you.
![image](https://user-images.githubusercontent.com/31803225/124268874-b7b55f80-db6c-11eb-9573-8280b41b5255.png)

**Comment by rebuilt** [comment]
Ok.  Great, have a good day.
