### ISSUE TITLE
[Bug]: Issue with new option on Dashboard (Neovim Config Files)

### ISSUE THREAD

**Issue by lakshyarao22** [ChristianChiarulli/LunarVim#623]
### Problem description

I have just updated the lunarvim config and trying the options,
Neovim Config Files is showing below error

### LunarVim version

0.30

### Neovim version (>= 0.5)

0.5

### Relevant log output

```shell
- ERROR: emmet_ls: The given command "emmet-ls" is not executable.
```

### Screenshots

![Screenshot_2021-07-03-54_1919x1079](https://user-images.githubusercontent.com/5268175/124363396-95990b80-dc58-11eb-85de-68599358b9fd.png)

### I have read

- [X] The readme
- [X] The wiki

**Comment by jameswalmsley** [comment]
This is happening because when your first start, the Telescope plugin has not loaded.
Run <leader>-f to open Telescope files ...

You should find that the config files option then works :)

I didn't look at how dashboard activates Telescope for the config files,
maybe it doesn't call the Telescope command and therefore the lazy-load isn't activated?

**Comment by jameswalmsley** [comment]
I've added a pull-request to telescope to make this work:

https://github.com/nvim-telescope/telescope.nvim/pull/955
