### ISSUE TITLE
[Bug]: Latex

### ISSUE THREAD

**Issue by barun108** [ChristianChiarulli/LunarVim#676]
### Problem description

How to setup Lsp fo Latex ?
How can I enable it 

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/nvim/ftplugin/)
- [X] I checked the options (~/.config/nvim/lv-config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

Latest

### Neovim version (>= 0.5)

nvim >=0.5

### Screenshots

![2021-07-05-091221_947x726_scrot](https://user-images.githubusercontent.com/12285528/124414862-2531dd80-dd71-11eb-99b3-d7d0d0dbf51a.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
output of lspinfo?

**Comment by PZ31k0nauT** [comment]
I had the experience that my latex-lsp was not up to date. I had to make a fresh install. TexLab which is used for the latex-lsp had an update with breaking changes. So make sure to run `:LspInstall latex` so that the lsp is up to date.

Regarding the setup of the latex-lsp I find these two pages pretty good:
- https://github.com/latex-lsp/texlab/blob/master/docs/options.md
- https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md

Maybe my PR will help you. So you have to wait a bit. #671

Today I will try to work on the preview settings. So that these are configurable for the user.

**Comment by barun108** [comment]
> output of lspinfo?

![2021-07-05-115947_455x235_scrot](https://user-images.githubusercontent.com/12285528/124427115-9466fc00-dd88-11eb-9621-c1f86fad5640.png)

**Comment by barun108** [comment]
> I had the experience that my latex-lsp was not up to date. I had to make a fresh install. TexLab which is used for the latex-lsp had an update with breaking changes. So make sure to run `:LspInstall latex` so that the lsp is up to date.
> 
> Regarding the setup of the latex-lsp I find these two pages pretty good:
> 
>     * https://github.com/latex-lsp/texlab/blob/master/docs/options.md
> 
>     * https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md
> 
> 
> Maybe my PR will help you. So you have to wait a bit. #671
> 
> Today I will try to work on the preview settings. So that these are configurable for the user.

I will try those settings and update here

and wait for the #671

**Comment by barun108** [comment]
Latest release has solved the issue :+1:
