### ISSUE TITLE
[Feature]: User should be able to choose formatting provider

### ISSUE THREAD

**Issue by abzcoding** [ChristianChiarulli/LunarVim#996]
### Feature motivation

some plugins support `vim.lsp.buf.formatting()` and they run faster than calling a cmd using `formatter.nvim`

an example would be `scala` using [nvim-metals](https://github.com/scalameta/nvim-metals) as talked about [here](https://github.com/ChristianChiarulli/LunarVim/pull/986#discussion_r671463631)

### Describe the expected solution

letting users override the autoformat capability to run `vim.lsp.formatting()` instead of `formatter.nvim` for specified languages

### Describe the alternatives you've considered

**1. overriding the keymap for it inside the `lua/lang/sth.lua`**
```lua
M.lsp = function()
-- ...
     O.user_which_key = {
       l = {
         f = { "<cmd>lua vim.lsp.buf.formatting()<cr>", "Format" },
       },
     }
-- ...
end
```
**2. add a new keymap and disable format_on_save and lint_on_save:**
```lua
M.config = function()
O.lang.sth ={
  formatters = {},
  linters = {},
}
end

M.lsp = function()
-- ...
     O.user_which_key = {
       l = {
         F = { "<cmd>lua vim.lsp.buf.formatting()<cr>", "Format with native lsp" },
       },
     }
-- ...
end
```

**3. and override/removing the `autoformat augroup`**

but it seems more like a hack than a solution

### Additional context

#986
#888
#1005

**Comment by sethigeet** [comment]
I guess we could add a function on to the global object (`_G`) and then call it in all the places from where formatting is done (autocmds, keybindings, etc.) and that function could check the formatter selected for the current `filetype` in the global options object (`O`) every time we format a file.

By adding the function to the global object(`_G`), it will be loaded at the start and hence will be very fast

**Comment by Tastyep** [comment]
First, about the which key mapping, I think that we should expose only one mapping for formatting, more mappings are just confusing for the user.
Also, the augroup for autoformatting should stay, we don't want to remove the functionality, we just want it to behave differently based on the user's settings.
As you know, both  of them (whichkey and augroup) call `FormatWrite`, the straightforward solution for adding a customization point would  be to use one function we would declare somewhere (maybe formatter.lua, maybe somewhere else) which would dispatch to the preferred way of formatting. This means this function will either call `vim.lsp.buf.formatting()` or `FormatWrite`.

In some lang files, we have this piece of code: `local ft = vim.bo.filetype`, it retrieves the file type. That could be useful because it would allow us to have access to `O.lang[ft]` and thus to the user configuration for that language.
I think that thanks to this, we have enough data to dispatch to the right formatting method.

There are some questions that still need to be discussed in order to be able to implement this correctly, for example:
- Would we allow both formatting from the lsp server and from the local tools at the same time ?
- What is the priority ? Probably lsp first and local tools second, do we agree on this ?
- How should be defined the configuration for the [lsp formatter](https://github.com/ChristianChiarulli/LunarVim/pull/1005/files#diff-029384eaacdb87ba47363c68c2809b6554cb8feca020aa9201221ae3af15e85cR11), `lang.lsp.formatter` is an option.

I'll give one example by assuming that:
- We don't allow both lsp and local formatting (this doesn't matter much actually, and is easy to implement)
- LSP formatting is prioritary
- LSP formatting configurations are defined under `O.lang[ft].lsp.formatter` like what follows:

``` lua
O.lang[ft].lsp = {
    path = "...",
    formatter = {
        flags = { ... },
        enabled = true
    },
    linter = {
        flags = { ... },
        enabled = true,
    }
}
```

Having this data structure, dispatching to either `vim.lsp.buf.formatting()` or `FormatWrite` should be easy.

Tell me what you think.

**Comment by abzcoding** [comment]
> First, about the which key mapping, I think that we should expose only one mapping for formatting, more mappings are just confusing for the user.
> Also, the augroup for autoformatting should stay, we don't want to remove the functionality, we just want it to behave differently based on the user's settings.
> As you know, both of them (whichkey and augroup) call `FormatWrite`, the straightforward solution for adding a customization point would be to use one function we would declare somewhere (maybe formatter.lua, maybe somewhere else) which would dispatch to the preferred way of formatting. This means this function will either call `vim.lsp.buf.formatting()` or `FormatWrite`.
> 
> In some lang files, we have this piece of code: `local ft = vim.bo.filetype`, it retrieves the file type. That could be useful because it would allow us to have access to `O.lang[ft]` and thus to the user configuration for that language.
> I think that thanks to this, we have enough data to dispatch to the right formatting method.
> 
> There are some questions that still need to be discussed in order to be able to implement this correctly, for example:
> 
>     * Would we allow both formatting from the lsp server and from the local tools at the same time ?
> 
>     * What is the priority ? Probably lsp first and local tools second, do we agree on this ?
> 
>     * How should be defined the configuration for the [lsp formatter](https://github.com/ChristianChiarulli/LunarVim/pull/1005/files#diff-029384eaacdb87ba47363c68c2809b6554cb8feca020aa9201221ae3af15e85cR11), `lang.lsp.formatter` is an option.
> 
> 
> I'll give one example by assuming that:
> 
>     * We don't allow both lsp and local formatting (this doesn't matter much actually, and is easy to implement)
> 
>     * LSP formatting is priority
> 
>     * LSP formatting configurations are defined under `O.lang[ft].lsp.formatter` like what follows:
> 
> 
> ```lua
> O.lang[ft].lsp = {
>     path = "...",
>     formatter = {
>         flags = { ... },
>         enabled = true
>     },
>     linter = {
>         flags = { ... },
>         enabled = true,
>     }
> }
> ```
> 
> Having this data structure, dispatching to either `vim.lsp.buf.formatting()` or `FormatWrite` should be easy.
> 
> Tell me what you think.

I think that is a great idea, but I rather wait for `nlsp-settings` and #1050 to finish and then implement this

**Comment by Tastyep** [comment]
I can check null-ls, is Chris taking care of `nlsp-settings` ?

**Comment by abzcoding** [comment]
> I can check null-ls, is Chris taking care of `nlsp-settings` ?

you can do that I think, yes chris is doing that in the `new_contract` branch

**Comment by ChristianChiarulli** [comment]
null-ls handles this by not needing to change the API
